// <auto-generated />
using System;
using HotelApiRestFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelApiRestFull.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241007150819_AddAllTablesAndSeeders")]
    partial class AddAllTablesAndSeeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HotelApiRestFull.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<int>("GuestId")
                        .HasColumnType("int")
                        .HasColumnName("guest_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<double>("TotalCost")
                        .HasColumnType("double")
                        .HasColumnName("total_cost");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("HotelApiRestFull.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("HotelApiRestFull.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthdate");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("guests");
                });

            modelBuilder.Entity("HotelApiRestFull.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("availability");

                    b.Property<string>("Number")
                        .HasColumnType("longtext")
                        .HasColumnName("room_number");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int")
                        .HasColumnName("max_occupancy_persons");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price_per_night");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            Number = "101",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            Number = "102",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            Number = "103",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            Number = "104",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            Number = "105",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            Number = "106",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            Number = "107",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Availability = true,
                            Number = "108",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Availability = true,
                            Number = "109",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Availability = true,
                            Number = "110",
                            Occupancy = 1,
                            Price = 50.0,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Availability = true,
                            Number = "201",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Availability = true,
                            Number = "202",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Availability = true,
                            Number = "203",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Availability = true,
                            Number = "204",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Availability = true,
                            Number = "205",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            Availability = true,
                            Number = "206",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            Availability = true,
                            Number = "207",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Availability = true,
                            Number = "208",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            Availability = true,
                            Number = "209",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Availability = true,
                            Number = "210",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Availability = true,
                            Number = "301",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 22,
                            Availability = true,
                            Number = "302",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            Availability = true,
                            Number = "303",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 24,
                            Availability = true,
                            Number = "304",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 25,
                            Availability = true,
                            Number = "305",
                            Occupancy = 2,
                            Price = 80.0,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 26,
                            Availability = true,
                            Number = "306",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 27,
                            Availability = true,
                            Number = "307",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 28,
                            Availability = true,
                            Number = "308",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 29,
                            Availability = true,
                            Number = "309",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 30,
                            Availability = true,
                            Number = "310",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 31,
                            Availability = true,
                            Number = "401",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 32,
                            Availability = true,
                            Number = "402",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 33,
                            Availability = true,
                            Number = "403",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            Availability = true,
                            Number = "404",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 35,
                            Availability = true,
                            Number = "405",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 36,
                            Availability = true,
                            Number = "406",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 37,
                            Availability = true,
                            Number = "407",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 38,
                            Availability = true,
                            Number = "408",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 39,
                            Availability = true,
                            Number = "409",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 40,
                            Availability = true,
                            Number = "410",
                            Occupancy = 2,
                            Price = 150.0,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 41,
                            Availability = true,
                            Number = "501",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 42,
                            Availability = true,
                            Number = "502",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 43,
                            Availability = true,
                            Number = "503",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 44,
                            Availability = true,
                            Number = "504",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 45,
                            Availability = true,
                            Number = "505",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 46,
                            Availability = true,
                            Number = "506",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 47,
                            Availability = true,
                            Number = "507",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 48,
                            Availability = true,
                            Number = "508",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 49,
                            Availability = true,
                            Number = "509",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 50,
                            Availability = true,
                            Number = "510",
                            Occupancy = 4,
                            Price = 200.0,
                            RoomTypeId = 4
                        });
                });

            modelBuilder.Entity("HotelApiRestFull.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("room_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Una acogedora habitación básica con una cama individual, ideal para viajeros solos.",
                            Name = "Habitacion Simple"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ofrece flexibilidad con dos camas individuales o una cama doble, perfecta para parejas o amigos.",
                            Name = "Habitacion Doble"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Espaciosa y lujosa, con una cama king size y una sala de estar separada, ideal para quienes buscan confort y exclusividad.",
                            Name = "Habitacion Suite"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Diseñada para familias, con espacio adicional y varias camas para una estancia cómoda.",
                            Name = "Habitacion Familiar"
                        });
                });

            modelBuilder.Entity("HotelApiRestFull.Models.Booking", b =>
                {
                    b.HasOne("HotelApiRestFull.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelApiRestFull.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelApiRestFull.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelApiRestFull.Models.Room", b =>
                {
                    b.HasOne("HotelApiRestFull.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });
#pragma warning restore 612, 618
        }
    }
}
